version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    groups:
      bundler-dependencies:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    groups:
      cargo:
        patterns:
          - "*"
